apiVersion: v1
kind: Pod
spec:
  containers:  
    - name: zip-job
      image: zip_job:0.1
      command: ["tail", "-f", "/dev/null"] 
      imagePullPolicy: Never 
      resources:  
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
    - name: gradle
      image: gradle:latest
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
      resources:  
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
