pipeline {
  agent {
    kubernetes {
      label 'zip_job'  
      idleMinutes 5  
      yamlFile 'task/build-pod.yaml'  
      defaultContainer 'zip-job'  
    }
  }
  stages {
    stage('Build-zip') {
      steps {  
        sh """
		cd task/out-files
		python3 /tmp/zip_job.py
	"""   
      }
    }
    stage('Build-app') {
      steps {  
        container('gradle') {
	  sh """
		cd task/hello-world-java/src
          	javac HelloWorld.java
          	ls
	"""
	}
      }
    }
    stage('Build Docker Image') {
      steps {
        container('docker') {  
          sh """
		cd task/hello-world-java
	  	docker build -t localhost:5000/hello-world:0.1 .
          	docker push localhost:5000/hello-world:0.1
	"""       
        }
      }
    }
  }
}
