pipeline {
  agent {
    kubernetes {
      label 'zip_job'  
      idleMinutes 5  
      yamlFile 'task/build-pod.yaml'  
      defaultContainer 'zip-job'  
    }
  }
  stages {
    stage('Build-zip') {
      steps {  
        sh "python zip_job.py"   
      }
    }
    stage('Build-app') {
      steps {  
        container('gradle') {
	  sh "cd task/hello-world-java/src"  
          sh "javac HelloWorld.java"
	}
      }
    }
    stage('Build Docker Image') {
      steps {
        container('docker') {  
          sh "cd task/hello-world-java"
	  sh "docker build -t hello-world:0.1 ."  
          sh "docker push hello-world:0.1"       
        }
      }
    }
  }
}
