import java.time.*
import java.text.SimpleDateFormat
import java.time.format.DateTimeFormatter

node {

   def now = LocalDateTime.now()
   def ECRegistry = "< aws acc id >.dkr.ecr.us-east-1.amazonaws.com"
   def repository = "count-app"
   def aws_region = "us-east-1"
   def ecs_cluster = "test-cluster"
   def ecs_task = "count-app"
   def ecs_service = "count-app" 
   def version = "0.1"

 
  stage('Checkout SCM') {
  	checkout scm
  }

  stage('Building image') {
	script {

                dockerImage = docker.build("${ECRegistry}/${repository}:${version}")

	}
  }

  stage('Push image') {
                String currDate = current_timestamp().toString()
		withDockerRegistry([url: "https://${ECRegistry}/${repository}"]) {
                        displayMessage("Push Image")
			def login = ecrLogin()
                        sh login
                	dockerImage.push("${version}")
                	dockerImage.push(currDate)
		}

  }

  
 stage ('Deploy on ECS')
       displayMessage("Deploy on ECS")
       withAWS(region: "${aws_region}") {
 	 sh "aws ecs update-service --region ${aws_region} --cluster ${ecs_cluster} --service ${ecs_service} --force-new-deployment"
	}
}


def displayMessage(message) {
    ansiColor('xterm') {
        echo "\033[44m  ${message} \033[0m"
    }
}


def current_timestamp() {
   def date = new Date()
   currDate = new SimpleDateFormat("ddMMyyyyHHmm")
   out = currDate.format(date)
   return out
}
